image: node:10-stretch

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy
cache:
  paths:
    - node_modules/

create_tag:
  image: maven:3.6.1-jdk-8
  stage: deploy
  only:
    - schedules
  script:
    - export VERSION=daily-build-harley-$(date +%Y%m%d)
    - curl --header "PRIVATE-TOKEN:${CI_PRIVATE_TOKEN}" --request POST "https://git.forwardx.ai/api/v4/projects/${CI_PROJECT_ID}/repository/tags?tag_name=${VERSION}&ref=${CI_COMMIT_REF_NAME}"
    - export VERSION=daily-build-xinwangda-$(date +%Y%m%d)
    - curl --header "PRIVATE-TOKEN:${CI_PRIVATE_TOKEN}" --request POST "https://git.forwardx.ai/api/v4/projects/${CI_PROJECT_ID}/repository/tags?tag_name=${VERSION}&ref=${CI_COMMIT_REF_NAME}"
    - export VERSION=daily-build-tcl-$(date +%Y%m%d)
    - curl --header "PRIVATE-TOKEN:${CI_PRIVATE_TOKEN}" --request POST "https://git.forwardx.ai/api/v4/projects/${CI_PROJECT_ID}/repository/tags?tag_name=${VERSION}&ref=${CI_COMMIT_REF_NAME}"

release log:
  stage: build
  only:
    - schedules
  tags:
    - logs
  script:
    - export NIGHT_PATH=/oss/nightly/$(date +%Y%m%d)/cluster
    - /oss/nightly/git_stat.sh

release build:
  stage: build
  only:
    - /^dev-.*$/
    - /^test-.*$/
    - /^tiemeng-.*$/
    - /^preprod-.*/
  except:
    - branches
  script:
    - ENV=${CI_COMMIT_TAG%%-*} suffix=${CI_COMMIT_TAG#*$ENV-} PROJECT=${suffix%%-*}
    - echo ${PROJECT}${ENV^}
    - npm install
    - npm run build --${PROJECT}${ENV^}
    - echo tag:${CI_COMMIT_TAG}-buildtime:$(date +%Y%m%d%H%M%S) > dist/.version.html
  artifacts:
    paths:
      - dist

delpoy to env:
  image: joec4i/ossutil
  stage: deploy
  environment:
    name: dev
  only:
    - /^dev-.*$/
    - /^test-.*$/
    - /^tiemeng-.*$/
    - /^preprod-.*/
  except:
    - branches
  script:
    - ENV=${CI_COMMIT_TAG%%-*} suffix=${CI_COMMIT_TAG#*$ENV-} PROJECT=${suffix%%-*}
    - echo "fe.${PROJECT}.${ENV}.internal.forwardx.com"
    - ossutil  -e oss-cn-beijing.aliyuncs.com --access-key-id ${ALIYUN_OSS_ACCESS_KEY_ID} --access-key-secret ${ALIYUN_OSS_ACCESS_KEY_SECRET}  cp -r -f  dist oss://k8s-test-dev-nginx-static/fe.${PROJECT}.${ENV}.internal.forwardx.com

release build test daily build:
  stage: build
  only:
    - /^daily-build.*$/
  except:
    - branches
  script:
    - ENV=test suffix=${CI_COMMIT_TAG#daily-build-*} PROJECT=${suffix%%-*}
    - |
      if [ "$PROJECT" = "xinwangda" ]; then
        export ENV=tiemeng
      fi
    - echo ${PROJECT}${ENV^}
    - npm install
    - npm run build --${PROJECT}${ENV^}
    - echo tag:${CI_COMMIT_TAG}-buildtime:$(date +%Y%m%d%H%M%S) > dist/.version.html
  artifacts:
    paths:
      - dist

delpoy to test daily build:
  image: joec4i/ossutil
  stage: deploy
  environment:
    name: test
  only:
    - /^daily-build.*$/
  except:
    - branches
  when: manual
  script:
    - ENV=test suffix=${CI_COMMIT_TAG#daily-build-*} PROJECT=${suffix%%-*}
    - |
      if [ "$PROJECT" = "xinwangda" ]; then
        export ENV=tiemeng
      fi
    - echo fe.${PROJECT}.${ENV}.internal.forwardx.com
    - ossutil  -e oss-cn-beijing.aliyuncs.com --access-key-id ${ALIYUN_OSS_ACCESS_KEY_ID} --access-key-secret ${ALIYUN_OSS_ACCESS_KEY_SECRET}  cp -r -f  dist oss://k8s-test-dev-nginx-static/fe.${PROJECT}.${ENV}.internal.forwardx.com

upload daily pipeline:
  image: joec4i/ossutil
  stage: build
  only:
    - /^daily-build.*$/
  except:
    - branches
  script:
    - suffix=${CI_COMMIT_TAG#daily-build-*} PROJECT=${suffix%%-*}
    - echo ${CI_PIPELINE_URL} > .pipeline_${CI_PROJECT_NAME}
    - ossutil  -e oss-cn-beijing.aliyuncs.com --access-key-id ${ALIYUN_OSS_ACCESS_KEY_ID} --access-key-secret ${ALIYUN_OSS_ACCESS_KEY_SECRET}  cp -r -f  .pipeline_${CI_PROJECT_NAME} oss://forwardx-nightly-pkg/nightly/$(date --date='TZ="Asia/Shanghai"' +%Y%m%d)/cluster/log/pipeline/${PROJECT}-${CI_PROJECT_NAME}.txt
